### ISSUE TITLE
Security concerns and questions

### ISSUE THREAD

**Issue by Mik13** [BirthdayResearch/defichain-electrum#4]
Hi!

Electrum-Wallet for DeFiChain is cool!
I've got a few questions to the changes you made.

https://github.com/BirthdayResearch/defichain-electrum/commit/4108015ae853b3d03e20616bb099e595a5e7e277#diff-4e452488a453f6ab6d869a6a006bfa23457727da1354a9f7a23126fc20f9842eR1046 interface.py
Doesn't the minus sign defeat the purpose of: "this ensures confirmed txs can't follow mempool txs" because prev_height gets negative and the height is then always greater because it's always positive?

https://github.com/BirthdayResearch/defichain-electrum/commit/4108015ae853b3d03e20616bb099e595a5e7e277#diff-33652baeb8cf51e4476fe0cc5d326185c2ee51065dc51727555bcae0910c7611L278
Why did you remove unix sockets?

https://github.com/BirthdayResearch/defichain-electrum/commit/4108015ae853b3d03e20616bb099e595a5e7e277#diff-570f8866ac2e8ec275df446db34dcf6f0fab2a0f4e853744a4543d8045a37455R314
Doesn't the "target > 0" prevent the checks after the if, target should always be bigger than 0 if I get that right?

Best regards!

**Comment by Mik13** [comment]
Hi!

I found another riddle:
https://github.com/BirthdayResearch/defichain-electrum/commit/4108015ae853b3d03e20616bb099e595a5e7e277#diff-3e2bc2ebf691eee5874df37d89f05e9b22786c97c80dd64ee4ebcf7b6ce2d474R298

Why did you change design model of the security checks from bool to raise? This will most likely introduce security vulnerabilities if you merge the current electrum into your project, when new checks are introduced and are returning bools which you do not verify but only catch exceptions.

I agree that raising exceptions would have been the securer way to do these checks, but changing it in an fork without pull requesting it into the original project is dangerous.

**Comment by ivan-zynesis** [comment]
Thanks for raising the concern.

I do agree that changing in a fork works like shortcut thus any call in this repo will not require any bool check. However changing in upstream will heavily impact others' downstream application and take forever to be merged in.

IMO, there is no real security vulnerability introduced as it is a solely a pre broadcast signature check function that happened on client side. And having no side effect on DeFiChain blockchain consensus.

Feel free to reopen the issue if you have different opinion.

Disclaimer: This repository is not actively maintained and not part of DeFiChain's team effort, no continuous maintenance could be expected.
