### ISSUE TITLE
Defichain ElectrumX Server @ 77.56.65.5:50001

### ISSUE THREAD

**Issue by Martin8617** [BirthdayResearch/defichain-electrum#8]
I have an additional Defichain ElectrumX Server "`77.56.65.5:50001`" running on the mainnet to serve the project.
If you like to use your Electrum Wallet with my node, you can choose mine or even use both servers.

**Comment by Martin8617** [comment]
I running in trouble with my mode while running the electrumX server. Till I find the reasson my ElectrumX Server may be won't run:

https://github.com/DeFiCh/ain/issues/1365

**Comment by anonimusek** [comment]
Hello, I need help with withdrawal my dfi token from Electrum
Please give me server to working network
Thank You!!
