### ISSUE TITLE
Withdrawal DFI Electreum

### ISSUE THREAD

**Issue by anonimusek** [BirthdayResearch/defichain-electrum#9]
Hello, I need help with withdrawal my dfi tokn from Electreum
Please give me server to working network
Thank You!!

**Comment by ivan-zynesis** [comment]
Our public server was down due technical issue, and it should be accessible again as described in the [README](https://github.com/BirthdayResearch/defichain-electrum/blob/master/README.rst). However, use any public server (included us) at your own risk. It is encouraged to run your own [defichain-electrumx](https://github.com/BirthdayResearch/defichain-electrumx) server to ensure server up time.

Disclaimer:
- This repository is not actively maintained and not part of DeFiChain's team effort, no continuous maintenance could be expected.
- Our public accessible defichain-electrumx server is meant for development purpose only.
